server:
  port: 9001

spring:
  application:
    name: eureka-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul-gateway
    prefer-ip-address: true     #访问路径可以显示IP地址

#zuul:
#  #ignored-services: microservicecloud-dept  #禁止真实服务名访问 单个
#  prefix: /qin  #加入访问前缀
#  ignored-services: "*"  #禁止真实服务名访问 所有
#  routes:
#    myprovider:
#      serviceId: eureka-provider  #真实服务名
#      path: /myprovider/**

