server:
  port: 8001

mybatis:
  type-aliases-package: com.qin.eurekaprovider1.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件

spring:
  application:
    name: eureka-provider
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01              # 当前数据库
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: eureka-provider8001
    prefer-ip-address: true     #访问路径可以显示IP地址
