server:
  port: 5353

spring:
  application:
    name: config
  profiles:
    active:
      - dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maple313/config.git
          search-paths: /**
      label: master
